---
title: "age_distribution"
author: "Brenda_Kiage"
date: "2023-07-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r load required libraries}

library(readxl)

library(ggplot2)

library(readr)

library(dplyr)

library(tidyr)


```


```{r obtain the age metadata}

festus_mdata <- read_xlsx("~/Downloads/festus_demograhic_and_lab_metadata.xlsx")
festus_mdata <- subset(festus_mdata, select=c("sequence_name", "age_years", "Lineage"))
festus_ids <- read_csv("~/Desktop/flub_msc/results/festus_id.csv")
festus_ids <- subset(festus_ids, select=c("isolate_name"))
colnames(festus_ids) <- "sequence_name"


festus_age_data <-merge(festus_ids,festus_mdata %>% select('sequence_name','age_years', 'Lineage'), by="sequence_name", all.x=TRUE)
festus_age_data <- drop_na(festus_age_data)
festus_age_data <- festus_age_data %>% separate(sequence_name, c("virus","location","id","year"))
festus_age_data <- subset(festus_age_data, select=c("year", "age_years", "Lineage"))

```


```{r obtain the age metadata}
sample_ages <- read_csv("~/Downloads/flub_ages.csv")

sample_mdata <- read_csv("~/Desktop/flub_msc/results/NS_data.csv")
sample_mdata <- subset(sample_mdata, select=c("phylogeny_name"))

sample_mdata <- sample_mdata %>% separate(phylogeny_name, c("study_no", "location", "collection_date"))
sample_mdata <- sample_mdata %>% separate(collection_date, c("year"))

sample_ages <-merge(sample_ages,sample_mdata %>% select('study_no','year'), by="study_no")
write_csv(sample_ages, "~/Desktop/sample_ages.csv")

sample_ages <- read_csv("~/Downloads/sample_ages_edit - sample_ages.csv")
sample_ages <- subset(sample_ages, select=c("year", "age_years", "Lineage"))

age_data <- rbind(sample_ages,festus_age_data)

age_data <- age_data %>% 
             group_by(Lineage, age_years) %>%
             summarise(counts = n()) %>%
             mutate(percentage= round(counts/171 * 100, 2))


```

```{r plot the age distribution line graph over time}

ggplot(age_data, aes(x=age_years, y=percentage, group=Lineage)) +
  geom_line(aes(color=Lineage), linetype="dashed") +
  theme_classic()+
  scale_color_brewer(palette="Dark2") +
  xlab("Age") +
    ylab("Percentage of IBV") +
    theme(axis.text = element_text(size = 10,
                                   colour = "black"),
          legend.position = "bottom")
 


  

```

